version: '2'
services:
  web:
    build: .
    command: python /code/app/app.py
    ports:
     - "8082:8082"
    volumes:
     - .:/code
    depends_on:
     - db
    env_file: .env
  db:
    image: mysql:5.6
    volumes:
      - data:/var/lib/mysql/data
    env_file: .env 
volumes:
  data:
    driver: local